### ISSUE TITLE
Cancelling Job not functional

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Arachne#36]
When I press the cancel button it takes some time for a message to appear on btm left (popup), suggest it immediately show the message.

Also it then after a while hangs on Aborting which suggest it is still not stopped.

<img width="1585" alt="image" src="https://github.com/OHDSI/Arachne/assets/7252105/7aa6e26e-f60f-47a4-ab66-ff54404070eb">

**Comment by dmitrys-odysseus** [comment]
The up-to-date state of the submission is only truly available to Execution Engine, datanode only received it at regular intervals.
ABORTING is a dedicated intermediate state to reflect that datanode is in the process of contacting EE to instruct it to abort submission. This state might transition to any of the following: 
ABORTED - EE has confirmed analysis was indeed aborted,
ABORT_FAILURE - unable to establish contact with execution engine
EXECUTED - analysis was completed successfully before the abort signal has reached EE
EXECUTION_FAILURE - analysis has failed before the abort signal has reached EE 

Showing such analysis as ABORTED is unacceptable because it will mislead users into believieving things that are not true, for example that EE resources are freed to rung new analysis.
Futhermore, a job stuck in the ABORTING state longer than 2 minutes must attract attention and trigger IT investigation, as the most likely cause for this is broken connection to EE, or having it so overloaded on CPU that is is not able to process the request.
